apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplybyte-pvc
spec:
  storageClassName: ""
  volumeName: simplybyte-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi